### PR TITLE
Add MUMPS routines that wrap the pass-by-reference XPAR routines

### PR DESCRIPTION
**Pull request by mfuroyama**
LOL!! Wait...whut? MUMPS? Sadly, yes...

Unfortunately, the GETLST and GETWP routines pass the results to a local parameter via pass-by-reference. There doesn't seem to be a way to properly call these functions via the NodeJS wrappers. These MUMPS routines are my attempt at wrapping those routines

The implementations wrap the original XPAR routines, creates a local var to pass-by-reference into the target function, then drops the result into the ^TMP global which the NodeJS wrappers *can* access.

Not sure this is the best solution though, so I'm putting the code up as a pull request.

### CODE REVIEW

**Comment by mfuroyama** [comment]
I should mention that this is merely one idea that popped out of a brainstorming session between me and @EdisonTing regarding the following Non-Clinical RPC issue: https://github.com/vistadataproject/nonClinicalRPCs/issues/2

**Comment by conorcaregraf** [comment]
Looks good.

> M ^TMP("ZVDPXPAR",$J,PAR)=WPTEXT

I'm not sure you need PAR and do include a comment on cleaning up TMP from Javascript. ie/ pre condition: K ^TMP("ZVDPXPAR",$J) and after read do same.

Otherwise, this is unavoidable unless you want to make string replies of your own in the MUMPS and I don't think that makes sense given that many RPCs do their own assembly of replies from many XPAR calls.

**Comment by conorcaregraf** [comment]
One last one - how about JSON? I forgot that. Given that the sizes is small for most of these parameter requests (isn't it?), we could return JSON and avoid the TMP? How would that look? Would that makes things easier?

**Comment by mfuroyama** [comment]
@conorcaregraf I like the JSON idea. Plus, it allows me to kill 2 birds with one stone: simplify the usage, and preclude the need for Killing the TMP global. I may have to "borrow" from the FMQL JSON code though...

**Comment by mfuroyama** [comment]
> does the WP text processing preserve the newlines? WP == multilined text so separated by \n.
> Could return an array of string ie/ text -> "lines" ... this way no need to worry about \n, \r etc as a > separator convention.

Yeah, this is a good idea since the code isn't doing anything extra WRT "special characters". I'll change the MUMPS to return an array of strings in the JSON.

> for GETLST, why the explicit length - isn't the array in JSON enough. People can do their own
> .length's?

To be totally honest, now that I look at the code this morning, I forget why I did that! I know I had a reason when I did it last night but it escapes me now. Drunk on the power of my newly-found MUMPS prowess, perhaps? 🤣 🤣 

Seriously though, you're right...it's redundant.  I'll pull it out.

> in the JSON wrapper, we can call these "proper" names like getValues (this is a parameter
> interface so why have "parameter" in the names?) and getWordProcessingValue

I'll remind @EdisonTing about this when he implements the JS wrapper

**Comment by mfuroyama** [comment]
This code/pull request is obviated by [KD's new Parameter Service branch](https://github.com/vistadataproject/VDM/pull/184).  Will close this without merge.

**Pull request closed without merging**
